# NewsBot Configuration Example

fetcher:
  period: "24h"  # Fetch news from the last 24 hours
  search_string: "chelsea fc"
  language: "en"
  region: "uk"

filter:
  confirmed_sources:
    - Chelsea FC
    - Chelsea Football Club
    - We Ain't Got No History
  accepted_sources:
    - Goal.com
    - Metro.co.uk
    - Evening Standard
    - The Independent
    - The Guardian
    - BBC Sport
    - Football.London
    - The Athletic
    - The Telegraph
    - The Mirror
    - Sky Sports
    - Sports Illustrated
  banned_headline_keywords:
    - "blahblahblah"
  banned_url_keywords:
    - "predicted"

deduplication:
  # Enable semantic deduplication using NLP (experimental, not yet implemented)
  enable_semantic: false
  # Similarity threshold for semantic deduplication (0.0-1.0)
  semantic_threshold: 0.8
  # Note: Semantic deduplication requires additional NLP libraries and models

scraper:
  # Timeout for HTTP requests in seconds
  timeout: 30
  # Maximum number of retry attempts for failed requests
  max_retries: 3
  # Delay between requests in seconds (rate limiting)
  delay_between_requests: 1.0

summarizer:
  max_length: 300
  retry_count: 5

# OpenAI configuration (non-sensitive settings)
openai:
  model: "gpt-4o-mini"        # GPT model to use for summarization
  max_tokens: 150             # Maximum tokens per API request
  temperature: 0.3            # Creativity level (0.0-1.0, lower = more focused)

rate_limit:
  post_interval_minutes: 5

relevance_checker:
  keywords:
    - "Chelsea"
    - "football"
  strategy: "substring"

storage:
  backend: "redis"
  redis_url: "redis://localhost:6379/0"

# Secrets (API keys, passwords) go in secrets.yaml
